<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Users\Administrator\Documents\Unified Functional Testing\GUITest36]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[GUITest36]]></DName>
<Res><![CDATA[Res7]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:30]]></Time>
<TimeTick>1678691610</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:30]]></Time>
<TimeTick>1678691610</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:44]]></Time>
<TimeTick>1678691624</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:44]]></Time>
<TimeTick>1678691624</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:44]]></Time>
<TimeTick>1678691624</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:44]]></Time>
<TimeTick>1678691624</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Action1" SourceLine="2" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:44]]></Time>
<TimeTick>1678691624</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="3" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:45]]></Time>
<TimeTick>1678691625</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:43:24" eTime="13-03-2023 - 12:43:45" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[GUITest36 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T13" iterID="2" >
<Action rID="T14">
<AName><![CDATA[Action1]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:46]]></Time>
<TimeTick>1678691626</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:46]]></Time>
<TimeTick>1678691626</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="32" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:58]]></Time>
<TimeTick>1678691638</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:58]]></Time>
<TimeTick>1678691638</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:58]]></Time>
<TimeTick>1678691638</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="38" Source="Action1" SourceLine="1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA[""]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:58]]></Time>
<TimeTick>1678691638</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" Source="Action1" SourceLine="2" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:58]]></Time>
<TimeTick>1678691638</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="Action1" SourceLine="3" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:43:58]]></Time>
<TimeTick>1678691638</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="37" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:43:45" eTime="13-03-2023 - 12:43:59" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="29" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="28" status="Passed" >
<Disp><![CDATA[GUITest36 Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T23" iterID="3" >
<Action rID="T24">
<AName><![CDATA[Action1]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:00]]></Time>
<TimeTick>1678691640</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:00]]></Time>
<TimeTick>1678691640</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="55" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="54" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:09]]></Time>
<TimeTick>1678691649</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:09]]></Time>
<TimeTick>1678691649</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["student"]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:09]]></Time>
<TimeTick>1678691649</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" Source="Action1" SourceLine="1" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Password123"]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:09]]></Time>
<TimeTick>1678691649</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" Source="Action1" SourceLine="2" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[WebButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:09]]></Time>
<TimeTick>1678691649</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="66" Source="Action1" SourceLine="3" >
<Disp><![CDATA[WebButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:10]]></Time>
<TimeTick>1678691650</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="59" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:43:59" eTime="13-03-2023 - 12:44:10" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="51" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="50" status="Passed" >
<Disp><![CDATA[GUITest36 Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T33" iterID="4" >
<Action rID="T34">
<AName><![CDATA[Action1]]></AName>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:18]]></Time>
<TimeTick>1678691658</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:18]]></Time>
<TimeTick>1678691658</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="77" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://practicetestautomation.com/practice-test-login/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="76" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:39]]></Time>
<TimeTick>1678691679</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:39]]></Time>
<TimeTick>1678691679</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[username]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"username"&nbsp;(of&nbsp;class&nbsp;WebEdit).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:39]]></Time>
<TimeTick>1678691679</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[username]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Type = text<br>Mercury Class = WebEdit<br>Html Tag = INPUT<br>_xpath = //INPUT[@id="username"]<br>|rows = 0<br>placeholder = <br>Name = username<br>Max Length = 524288<br>Html Id = username<br>default value = <br>DHTML Class = <br>acc_name = <br>]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:39]]></Time>
<TimeTick>1678691679</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="108" status="Warning" nType="Description" Source="Action1" SourceLine="1" >
<Disp><![CDATA[username]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="107" status="Failed" nType="Run Error" Source="Action1" SourceLine="1" >
<Disp><![CDATA[username]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="106" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="105" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:39]]></Time>
<TimeTick>1678691679</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Test Login | Practice]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:39]]></Time>
<TimeTick>1678691679</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;username&quot; (of class WebEdit).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (2): &quot;Browser(&quot;Test Login | Practice&quot;).Page(&quot;Test Login | Practice&quot;).WebEdit(&quot;username&quot;).Set DataTable(&quot;username1&quot;, dtGlobalSheet)&quot;. ]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:40]]></Time>
<TimeTick>1678691680</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="111" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[13-03-2023 - 12:44:49]]></Time>
<TimeTick>1678691689</TimeTick>
<NodeArgs eType="General" icon="11" nRep="112" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="110" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="109" status="Failed" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Test Login | Practice]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:44:10" eTime="13-03-2023 - 12:44:49" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="73" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="72" status="Failed" >
<Disp><![CDATA[GUITest36 Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-03-2023 - 12:43:18" eTime="13-03-2023 - 12:44:49" passed="4" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test GUITest36 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>